#!/bin/bash
#
# Build an executable binary
#
# This target uses 'go build' to build an executable
# for the target platform, in the configured path.
#

# Get rid of existing binary
rm -f "${COACH_BUILD_BINARY_PATH}"

BUILDTIME=$(date --rfc-3339 ns | sed -e 's/ /T/') &> /dev/null
GITCOMMIT=$(git rev-parse --short HEAD)

echo "  --> Building ${COACH_BUILD_BINARY_PATH}"

mkdir -p "${COACH_BUILD_PATH}"

# Build cli binaries
go build \
   -p 2 \
   -v \
   -ldflags="-w -X ${COACH_PKG}/version.GITCOMMIT=${GITCOMMIT} -X ${COACH_PKG}/version.BUILDTIME=${BUILDTIME} -X ${COACH_PKG}/version.SHOWWARNING=${SHOWWARNING}" \
   -o "${COACH_BUILD_BINARY_PATH}" \
   ./coach