#!/bin/bash
#
# Install the built binary somewhere useful
#
# This puts the build result in a useful place,
# depending on make configuration
#

echo "  --> Installing compiled binaries"

for TARGET in ${COACH_COMMANDS_PATH}/*; do
    if [ -d "${TARGET}" ]; then
        NAME=${TARGET##*/}
        BUILD_PATH="${COACH_BUILD_PATH}/${NAME}"
        INSTALL_PATH="${COACH_INSTALL_PATH}/${NAME}"

        echo "      - Installing $NAME [${BUILD_PATH} -> ${INSTALL_PATH}]"

        (
            cp "${BUILD_PATH}" "${INSTALL_PATH}"
        )
    fi
done
