#!/bin/bash

for TARGET in $COACH_GO_TARGETS; do
    (
        echo "---> Running tests in $TARGET"
        cd "$TARGET"

        {

            go test $(go list ./... | grep -v vendor) &&
            echo "PASS"

        } || { # catch
            echo "FAIL"
        }


    )
done
