#!/bin/bash

for TARGET in $COACH_GO_TARGETS; do
    (
        echo "---> Running tests in $TARGET"
        cd "$TARGET"


            for PACKAGE in $(go list ./... | grep -v vendor); do

                {



                    go test $PACKAGE &&
                    echo "tested [$PACKAGE] : PASS"

                } || { # catch
                    echo "tested [$PACKAGE] : FAIL"
                }

            done

    )
done
